"""empty message

Revision ID: 44e3e0e93a1d
Revises: 8b348cb5fa6c
Create Date: 2022-09-14 23:18:44.424130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44e3e0e93a1d'
down_revision = '8b348cb5fa6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('characters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('dimension', sa.String(length=20), nullable=False),
    sa.Column('alive', sa.Boolean(), nullable=False),
    sa.Column('species', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('episodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('air_date', sa.String(length=20), nullable=False),
    sa.Column('alive', sa.Boolean(), nullable=False),
    sa.Column('species', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('episodes')
    op.drop_table('characters')
    # ### end Alembic commands ###
